### ISSUE TITLE
How do you run this confused code in train.py:168:8 ？

### ISSUE THREAD

**Issue by feipiao594** [KOKOMI12345/genshin-character-analysis-pytorch-pro#1]
![image](https://github.com/KOKOMI12345/genshin-character-analysis-pytorch-pro/assets/109599393/53a0b28d-8e2b-4fde-9575-1289193a27f8)
这里  `config` 未实例化，导致 `Config.train_continue` 其中并没有一个正常的 bool 值，我们尝试复用这个模型做音频分类时，发现了这些问题，请问是什么原因呢

**Comment by feipiao594** [comment]
![image](https://github.com/KOKOMI12345/genshin-character-analysis-pytorch-pro/assets/109599393/53a0b28d-8e2b-4fde-9575-1289193a27f8)
这里  `config` 未实例化，导致 `Config.train_continue` 其中并没有一个正常的 bool 值，我们尝试复用这个模型做音频分类时，发现了这些问题，请问是什么原因呢

**Comment by ghost** [comment]
非常抱歉，犯了一个低级错误，原因是因为，在访问Config类的属性前没有实例化属性，导致得到的布尔值不正常，我已经修复，正在update




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KOKOMI12345/genshin-character-analysis-pytorch-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月29日(星期五) 下午2:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [KOKOMI12345/genshin-character-analysis-pytorch-pro] How (Issue #1)





 
image.png (view on web)
 这里  config 未实例化，导致 Config.train_continue 其中并没有一个正常的 bool 值，我们尝试复用这个模型做音频分类时，发现了这些问题，请问是什么原因呢

**Comment by ghost** [comment]
更新完成

**Comment by SUC-DriverOld** [comment]
这是我webui预处理时的输出界面：
![image](https://github.com/KOKOMI12345/genshin-character-analysis-pytorch-pro/assets/75163782/46436256-96dc-43db-bd1c-07f7c22811ca)
能正确输出success

但是在实际操作过程中，我并没有在model/{name}路径下发现自动创建character.txt，所以我并不知道此txt的具体格式，但是我根据character.py中的内容，自己编写了如下的character.txt

```
character = {
    "1": "01"
}
```

然后这是我的datasets文件夹目录

```
datasets
└─test
    ├─testing
    │  └─01
     |      └─xxx.wav
     |      └─......
    │  └─02
     |      └─xxx.wav
     |      └─......
    ├─train
    │  └─01
     |      └─xxx.wav
     |      └─......
    │  └─02
     |      └─xxx.wav
     |      └─......
    └─validate
        └─01
            └─xxx.wav
            └─......
       └─02
            └─xxx.wav
            └─......
```

随后我点击首次训练，出现如下报错：

```
[14:32:38][MainThread/CRITICAL][exception_hook]:发生异常:
An Fatal Error has occurred: FileNotFoundError: [Errno 2] No such file or directory: './model/全角色/info.json'
Traceback (most recent call last):
  at <module> in (E:\AI\genshin-character-analysis-pytorch-pro-main\train.py:169)
```

根据报错信息，我将train.py的第165行改为我的训练文件夹名字：`name = "test"`然后进行调试

![image](https://github.com/KOKOMI12345/genshin-character-analysis-pytorch-pro/assets/75163782/039900d6-1b27-457b-a57d-9fc6660a8834)

![image](https://github.com/KOKOMI12345/genshin-character-analysis-pytorch-pro/assets/75163782/60d40c4b-add5-4ac2-9c0c-c5652dcd3388)


但事实上，Line181的if判断`if Config.train_countinue`的`Config.train_countinue`字段对应的值是false，理论上不应该进入if语句，而是直接进入else

根据调试信息，Config.train_countinue并没有进行实例化，而是仅开辟了一块内存

**Comment by SUC-DriverOld** [comment]
此外我也非常希望您解释一下character.txt中应该填入什么内容，谢谢回答
